### ISSUE TITLE
task 4 missing

### ISSUE THREAD

**Issue by ratnanil** [christiankrahenbuhl/cma-week2#12]
https://github.com/christiankrahenbuhl/cma-week2/blob/3f2cd1da79cae611c4472a417ba3212e9a2fd5f2/week2-rexercise.R#L110-L110<br/><br/>
see: https://computationalmovementanalysis.github.io/W02_05_tasks_and_inputs.html

> Visualize the output from your moving windows and compare different window sizes (k =)

you only have one window size and no visualisation

**Comment by christiankrahenbuhl** [comment]
I did not understand the exercise here, should I do it like this but for different window sizes?

caro %>%
  mutate(rspeed= rollmean(speed, 10, align="left",fill=0)) %>%
  ggplot(aes(x=DatetimeUTC,y=speed)) +
  geom_col(fill="pink")+
  geom_line(aes(x=DatetimeUTC,y = rspeed), color = "red")

**Comment by ratnanil** [comment]
yes!

**Comment by christiankrahenbuhl** [comment]
Thank you, committed & pushed!
