### ISSUE TITLE
task 3 not complete 

### ISSUE THREAD

**Issue by ratnanil** [christiankrahenbuhl/cma-week2#13]
https://github.com/christiankrahenbuhl/cma-week2/blob/3f2cd1da79cae611c4472a417ba3212e9a2fd5f2/week2-rexercise.R#L105-L107<br/><br/>

> compare the speeds visually in a line plot and also visualize the trajectories in a map

this plot does not compare different subsets

**Comment by christiankrahenbuhl** [comment]
Fixed! (pushed)
