### ISSUE TITLE
wildschwein_BE_2056.csv missing

### ISSUE THREAD

**Issue by ratnanil** [christiankrahenbuhl/cma-week2#3]
https://github.com/christiankrahenbuhl/cma-week2/blob/3f2cd1da79cae611c4472a417ba3212e9a2fd5f2/week2-rexercise.R#L8-L8<br/><br/>your repo is not self suffucient: This file is missing from your repo!

**Comment by christiankrahenbuhl** [comment]
Oh, I didn't think I should upload the datasets, makes sense, thank you!
