### ISSUE TITLE
timelag? 

### ISSUE THREAD

**Issue by ratnanil** [christiankrahenbuhl/cma-week2#6]
https://github.com/christiankrahenbuhl/cma-week2/blob/3f2cd1da79cae611c4472a417ba3212e9a2fd5f2/week2-rexercise.R#L44-L44<br/><br/>where was this variable created?

**Comment by christiankrahenbuhl** [comment]
What do you mean by "where" please? 
Isn't it created through this line?

**Comment by ratnanil** [comment]
resolved when resolving  #5
